import { useMemo, useState } from 'react';
import { Download, Printer, TrendingUp } from 'lucide-react';
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useERP } from '../../context/ERPContext';
import { forecastHistory, projectForecast } from '../../lib/forecastReports';
import { buildAccountingReports, csvText, downloadText, printReport, reportHtml, type ReportSection } from '../../lib/accountingReports';
import { formatCurrencyUSD as usd } from '../../utils/salvadoranTax';
const input = 'w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 px-3 py-2 text-sm mt-1';
const button = 'inline-flex items-center gap-2 px-3 py-2 text-sm rounded-lg border border-slate-200 dark:border-slate-700';
export function ForecastingModule() {
  const { invoices, purchases, bankAccounts, journalEntries, chartOfAccounts, currentCompany } = useERP();
  const [months, setMonths] = useState(6), [growth, setGrowth] = useState(0), [collection, setCollection] = useState(100), [supplierPayment, setSupplierPayment] = useState(100);
  const [ratio, setRatio] = useState<number | null>(null), [expense, setExpense] = useState<number | null>(null);
  const [manual, setManual] = useState(false), [manualSales, setManualSales] = useState(0), [message, setMessage] = useState('');
  const now = new Date(), monthKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  const history = useMemo(() => forecastHistory(invoices, purchases), [invoices, purchases, monthKey]);
  const recordedMonths = history.filter(month => month.recorded).length;
  const historicSales = history.reduce((sum, month) => sum + month.sales, 0), historicPurchases = history.reduce((sum, month) => sum + month.purchases, 0);
  const purchaseRatio = ratio ?? (historicSales > 0 ? Math.max(0, historicPurchases / historicSales * 100) : 0);
  const lastMonth = history.at(-1)!.month;
  const realExpense = buildAccountingReports(chartOfAccounts, journalEntries, bankAccounts, `${lastMonth}-01`, `${lastMonth}-31`).expenses;
  const budgetExpense = expense ?? Math.max(0, realExpense);
  const opening = bankAccounts.reduce((sum, account) => sum + account.currentBalance, 0);
  let rows: ReturnType<typeof projectForecast> = [], error = '';
  try { rows = projectForecast(history, { months, growth, purchaseRatio, collection, supplierPayment, expense: budgetExpense, opening, ...(manual ? { manualSales } : {}) }); } catch (exception) { error = (exception as Error).message; }
  const section: ReportSection = { title: manual ? 'Simulación con ventas ingresadas manualmente' : 'Proyección basada en registros', headers: ['Mes', 'Ventas sin IVA', 'Compras sin IVA', 'Cobros estimados', 'Pagos estimados', 'Cambio en efectivo', 'Efectivo final'], rows: rows.map(row => [row.month, row.sales, row.purchases, row.inflow, row.outflow, row.net, row.closing]), note: `Estimación, no garantía. Crecimiento mensual ${growth}%; compras/ventas ${purchaseRatio.toFixed(2)}%; cobro en el mes ${collection}%; pago de compras ${supplierPayment}%; gastos mensuales ${usd(budgetExpense)}. Parte del saldo actual ${usd(opening)} y proyecta desde el próximo mes, sin estimar el resto del mes en curso. No incluye IVA, impuestos, deudas anteriores, inversiones ni préstamos futuros.` };
  const safe = (action: () => void) => { try { action(); setMessage(''); } catch (exception) { setMessage((exception as Error).message); } };
  const sum = (field: 'sales' | 'purchases' | 'net') => rows.reduce((sum, row) => sum + row[field], 0);
  const field = (label: string, value: number, update: (value: number) => void, min = 0, max?: number) => <label className="text-sm text-slate-600 dark:text-slate-300">{label}<input aria-label={label} className={input} type="number" min={min} max={max} step="0.01" value={Math.round(value * 100) / 100} onChange={event => update(Number(event.target.value))} /></label>;
  return <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-6 text-slate-800 dark:text-slate-100">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-teal-700">Planificación del negocio</p><h1 className="text-2xl font-semibold mt-1">Pronósticos de ventas y efectivo</h1><p className="text-sm text-slate-500 mt-2">Explora qué pasaría con tus ventas, compras y dinero disponible.</p></div><div className="flex gap-2"><button disabled={!rows.length} className={`${button} disabled:opacity-40`} onClick={() => downloadText(`proyeccion-${monthKey}.csv`, csvText([section.headers, ...section.rows]))}><Download size={16} />Excel (CSV)</button><button disabled={!rows.length} className={`${button} disabled:opacity-40`} onClick={() => safe(() => printReport(reportHtml(currentCompany.tradeName || currentCompany.name, currentCompany.nit, 'Proyección · USD', [section])))}><Printer size={16} />Imprimir / PDF</button></div></div>
    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 p-5 rounded-xl space-y-4"><h2 className="font-semibold flex items-center gap-2"><TrendingUp size={18} className="text-teal-700" />Ajusta tus supuestos</h2><p className="text-sm text-slate-500">Se usan los últimos 12 meses completos ({recordedMonths} con registros). La base es el promedio de los últimos 3 meses desde que hay actividad; los meses sin ventas cuentan como cero. Las compras no equivalen al costo de los productos vendidos.</p><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4"><label className="text-sm">Proyectar<select className={input} value={months} onChange={event => setMonths(Number(event.target.value))}><option value={3}>3 meses</option><option value={6}>6 meses</option><option value={12}>12 meses</option></select></label>{field('Crecimiento mensual de ventas (%)', growth, setGrowth, -100, 100)}{field('Compras respecto a ventas (%)', purchaseRatio, setRatio)}{field('Ventas cobradas en el mismo mes (%)', collection, setCollection, 0, 100)}{field('Compras pagadas en el mismo mes (%)', supplierPayment, setSupplierPayment, 0, 100)}{field('Gastos mensuales pagados ($)', budgetExpense, setExpense)}</div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={manual} onChange={event => setManual(event.target.checked)} />Quiero usar una base de ventas manual para simular</label>{manual && <div className="max-w-sm">{field('Ventas mensuales de partida sin IVA ($)', manualSales, setManualSales)}</div>}<p className="text-xs text-slate-500">El porcentaje que no se cobra o paga en el mes queda fuera de este escenario. No se presupone que se cobre después. Los gastos parten del último mes contabilizado y puedes ajustar el importe.</p></div>
    {(error || message) && <p role="alert" className="p-4 bg-amber-50 text-amber-900 rounded-lg">{error || message}</p>}
    {!rows.length && !error && <div className="p-6 border border-slate-200 dark:border-slate-700 rounded-xl bg-white dark:bg-slate-900"><h2 className="font-semibold">Todavía falta historial para pronosticar</h2><p className="text-sm text-slate-500 mt-2">Registra actividad en al menos 3 meses completos, o activa una base manual para explorar un escenario. No se añaden ventas de ejemplo a tus datos.</p></div>}
    {rows.length > 0 && <><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[['Ventas proyectadas', sum('sales')], ['Compras proyectadas', sum('purchases')], ['Cambio en efectivo', sum('net')], ['Efectivo final estimado', rows.at(-1)!.closing]].map(([label, value]) => <div key={label} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl p-5"><p className="text-sm text-slate-500">{label}</p><p className="text-2xl font-semibold mt-2">{usd(Number(value))}</p></div>)}</div><div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl p-5"><h2 className="font-semibold mb-4">{manual ? 'Escenario manual' : 'Escenario según tu historial'}</h2><div className="w-full min-w-0" style={{ height: 300 }}><ResponsiveContainer width="100%" height={300} minWidth={0}><LineChart data={rows}><CartesianGrid vertical={false} strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 11 }} /><YAxis width={70} tickFormatter={value => `$${value}`} tick={{ fontSize: 11 }} /><Tooltip formatter={value => usd(Number(value))} /><Legend /><Line dataKey="sales" name="Ventas" stroke="#0f766e" isAnimationActive={false} /><Line dataKey="purchases" name="Compras" stroke="#64748b" isAnimationActive={false} /><Line dataKey="closing" name="Efectivo al final" stroke="#d97706" isAnimationActive={false} /></LineChart></ResponsiveContainer></div></div><div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 dark:bg-slate-800"><tr>{section.headers.map(header => <th key={header} className="text-left p-3 whitespace-nowrap">{header}</th>)}</tr></thead><tbody>{section.rows.map((row, index) => <tr key={index} className="border-t border-slate-100 dark:border-slate-800">{row.map((value, column) => <td key={column} className="p-3 whitespace-nowrap">{typeof value === 'number' ? usd(value) : value}</td>)}</tr>)}</tbody></table></div>{rows.some(row => row.closing < 0) && <p className="p-4 rounded-lg bg-amber-50 text-amber-900 text-sm">Este escenario deja el efectivo por debajo de cero. Revisa fechas de cobro, compras y gastos antes de comprometer pagos.</p>}<p className="text-xs text-slate-500">{section.note}</p></>}
  </div>;
}
