import {
  Company,
  Branch,
  UserProfile,
  Product,
  Customer,
  Supplier,
  Employee,
  BankAccount,
  Invoice,
  Purchase,
  Payroll,
  JournalEntry,
  KardexMovement,
  DynamicChartWidget,
  OtherIncome,
  ProfessionalServiceRecord,
  CandidateFolder,
  CandidateApplicant,
} from '../types';
import { DEFAULT_FISCAL_CONFIG } from './salvadoranTax';

export const SAMPLE_BRANCHES: Branch[] = [
  {
    id: 'branch_1',
    companyId: 'comp_1',
    code: 'SUC-01',
    name: 'Casa Matriz - Escalón',
    address: 'Torre Futura, Nivel 14, Col. Escalón, San Salvador',
    department: 'San Salvador',
    municipality: 'San Salvador Centro (San Salvador, Mejicanos, Ayutuxtepeque, Cuscatancingo, Ciudad Delgado)',
    phone: '+503 2244-8800',
    managerName: 'Ing. Rodrigo Melgar',
    isMain: true,
    isActive: true,
  },
  {
    id: 'branch_2',
    companyId: 'comp_1',
    code: 'SUC-02',
    name: 'Sucursal Santa Tecla',
    address: 'Centro Comercial Las Ramblas, Local 18, Santa Tecla',
    department: 'La Libertad',
    municipality: 'La Libertad Centro (Santa Tecla, Antiguo Cuscatlán)',
    phone: '+503 2288-9900',
    managerName: 'Claudia Morales',
    isMain: false,
    isActive: true,
  },
  {
    id: 'branch_3',
    companyId: 'comp_1',
    code: 'SUC-03',
    name: 'Sucursal San Miguel',
    address: 'Avenida Roosevelt Sur #402, San Miguel',
    department: 'San Miguel',
    municipality: 'San Miguel Centro (San Miguel, Comacarán, Ullazapa)',
    phone: '+503 2661-4400',
    managerName: 'José Mario López',
    isMain: false,
    isActive: true,
  },
];

export const SAMPLE_USERS: UserProfile[] = [
  {
    id: 'user_david',
    name: 'David (Super Admin)',
    email: 'davidinn234@gmail.com',
    password: 'admin',
    role: 'admin_maestro',
    dui: '01234567-9',
    nit: '0614-010190-101-1',
    phone: '+503 7000-0000',
    jobTitle: 'Super Administrador / Propietario Plataforma',
    department: 'San Salvador',
    municipality: 'San Salvador',
    systemArchetype: 'empresa_consolidada_dte',
    isConfigured: true,
  },
  {
    id: 'user_emprendedor',
    name: 'Mauricio Quintanilla (Emprendedor)',
    email: 'emprendedor@sivarflow.sv',
    password: 'admin',
    role: 'admin_maestro',
    dui: '02345678-0',
    nit: '0614-150692-103-5',
    phone: '+503 7111-2233',
    jobTitle: 'Propietario / Negocio Emprendedor',
    department: 'San Salvador',
    municipality: 'Mejicanos',
    systemArchetype: 'emprendedor_control_interno',
    isConfigured: true,
  },
  {
    id: 'user_admin',
    name: 'Administrador Maestro',
    email: 'admin@sivarflow.sv',
    password: 'admin',
    role: 'admin_maestro',
    dui: '02345678-9',
    nit: '0614-120588-102-4',
    phone: '+503 7890-1234',
    jobTitle: 'Director General / Administrador del Sistema',
    department: 'San Salvador',
    municipality: 'San Salvador',
    systemArchetype: 'empresa_consolidada_dte',
    isConfigured: true,
  },
  {
    id: 'user_1',
    name: 'Lic. Carlos Henríquez',
    email: 'carlos@sivarflow.sv',
    password: 'admin',
    role: 'admin_maestro',
    dui: '01234567-8',
    nit: '0614-250390-101-2',
    phone: '+503 7123-4567',
    jobTitle: 'Gerente General & Fundador',
    department: 'San Salvador',
    municipality: 'San Salvador',
    systemArchetype: 'empresa_consolidada_dte',
    isConfigured: true,
  },
  {
    id: 'user_2',
    name: 'Licda. Brenda Marroquín (CPA)',
    email: 'contabilidad@sivarflow.sv',
    password: 'admin',
    role: 'contador',
    dui: '03456789-1',
    phone: '+503 7234-5678',
    jobTitle: 'Contadora General (CPA Autorizada)',
    department: 'La Libertad',
    municipality: 'Santa Tecla',
    systemArchetype: 'empresa_consolidada_dte',
    isConfigured: true,
  },
  {
    id: 'user_3',
    name: 'Ing. Rodrigo Melgar',
    email: 'operaciones@sivarflow.sv',
    password: 'admin',
    role: 'gerente',
    dui: '04567890-2',
    phone: '+503 7345-6789',
    jobTitle: 'Jefe de Operaciones & Logística',
    department: 'San Salvador',
    municipality: 'Antiguo Cuscatlán',
    systemArchetype: 'empresa_consolidada_dte',
    isConfigured: true,
  },
  {
    id: 'user_4',
    name: 'Sofía Palacios',
    email: 'caja@sivarflow.sv',
    password: 'admin',
    role: 'cajero',
    dui: '05678901-3',
    phone: '+503 7456-7890',
    jobTitle: 'Encargada de Facturación & POS',
    department: 'San Salvador',
    municipality: 'San Salvador',
    systemArchetype: 'empresa_consolidada_dte',
    isConfigured: true,
  },
  {
    id: 'user_personal',
    name: 'Kevin Alexander Ramos',
    email: 'personal@sivarflow.sv',
    password: 'admin',
    role: 'admin_maestro',
    dui: '06789012-4',
    phone: '+503 7567-8901',
    jobTitle: 'Profesional Independiente / Finanzas Propias',
    department: 'La Libertad',
    municipality: 'Colón',
    systemArchetype: 'finanzas_personales',
    isConfigured: true,
  },
];

export const SAMPLE_COMPANIES: Company[] = [
  {
    id: 'comp_1',
    name: 'SivarTech Solutions S.A. de C.V.',
    tradeName: 'SivarTech Solutions - Software & Cloud ERP',
    nit: '0614-010121-102-1',
    nrc: '298714-3',
    giro: 'Desarrollo de Software Empresarial y Consultoría Cloud',
    address: 'Torre Futura, Nivel 14, Col. Escalón, San Salvador',
    department: 'San Salvador',
    phone: '+503 2244-8800',
    email: 'contacto@sivartech.sv',
    isGranContribuyente: true,
    currency: 'USD',
    fiscalYear: 2026,
    fiscalConfig: { ...DEFAULT_FISCAL_CONFIG },
    regimeType: 'general_tributario',
    dteActive: true,
    taxesConfig: {
      declaIva: true,
      declaPagoCuenta: true,
      declaImpuestosMunicipales: true,
      municipalRateOrFee: 45.00,
      alcaldiaName: 'Alcaldía Municipal de San Salvador Centro',
    },
  },
  {
    id: 'comp_2',
    name: 'Distribuidora Cuscatleca S.A. de C.V.',
    tradeName: 'Distribuidora Cuscatleca',
    nit: '0511-150819-101-9',
    nrc: '184920-5',
    giro: 'Comercialización y Distribución Mayorista de Tecnología y Accesorios',
    address: 'Paseo General Escalón #3920, San Salvador',
    department: 'San Salvador',
    phone: '+503 2511-7700',
    email: 'ventas@distribuidoracuscatleca.com',
    isGranContribuyente: false,
    currency: 'USD',
    fiscalYear: 2026,
    fiscalConfig: { ...DEFAULT_FISCAL_CONFIG },
    regimeType: 'general_tributario',
    dteActive: true,
    taxesConfig: {
      declaIva: true,
      declaPagoCuenta: true,
      declaImpuestosMunicipales: true,
      municipalRateOrFee: 30.00,
      alcaldiaName: 'Alcaldía Municipal de San Salvador Centro',
    },
  },
  {
    id: 'comp_3',
    name: 'Café & Tienda Santa Tecla / Emprendimiento',
    tradeName: 'Café & Tienda Santa Tecla',
    nit: '0614-220422-105-4',
    nrc: '319402-1',
    giro: 'Servicio de Alimentos, Bebidas y Venta de Mostrador',
    address: 'Paseo El Carmen #12, Santa Tecla, La Libertad',
    department: 'La Libertad',
    phone: '+503 2288-4411',
    email: 'hola@cafesantatecla.sv',
    isGranContribuyente: false,
    currency: 'USD',
    fiscalYear: 2026,
    fiscalConfig: { ...DEFAULT_FISCAL_CONFIG },
    regimeType: 'emprendedor_control_interno',
    dteActive: false,
    taxesConfig: {
      declaIva: false,
      declaPagoCuenta: false,
      declaImpuestosMunicipales: true,
      municipalRateOrFee: 15.00,
      alcaldiaName: 'Alcaldía Municipal de Santa Tecla',
    },
  },
];

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    companyId: 'comp_1',
    code: 'SRV-ERP-01',
    barcode: '7411000000019',
    name: 'Licencia FinaPyme ERP Anual (Cloud SaaS)',
    category: 'Software & SaaS',
    unit: 'Licencia',
    salePrice: 1200.00,
    currentCost: 350.00,
    stock: 999,
    minStock: 10,
    location: 'Cloud Data Center',
    isService: true,
  },
  {
    id: 'prod_2',
    companyId: 'comp_1',
    code: 'SRV-CONS-02',
    barcode: '7411000000026',
    name: 'Consultoría e Implementación NIIF / DTE MH',
    category: 'Servicios Profesionales',
    unit: 'Hora/Servicio',
    salePrice: 85.00,
    currentCost: 35.00,
    stock: 999,
    minStock: 5,
    location: 'Oficinas Cliente / Remoto',
    isService: true,
  },
  {
    id: 'prod_3',
    companyId: 'comp_1',
    code: 'HW-POS-03',
    barcode: '7411000000033',
    name: 'Terminal Touchscreen POS DTE + Impresora Térmica 80mm',
    category: 'Hardware & POS',
    unit: 'Unidad',
    salePrice: 480.00,
    currentCost: 310.00,
    stock: 24,
    minStock: 6,
    location: 'Bodega Central Escalón',
    isService: false,
  },
  {
    id: 'prod_4',
    companyId: 'comp_1',
    code: 'HW-SCAN-04',
    barcode: '7411000000040',
    name: 'Lector Láser de Código de Barras y QR 2D',
    category: 'Hardware & POS',
    unit: 'Unidad',
    salePrice: 75.00,
    currentCost: 42.00,
    stock: 45,
    minStock: 10,
    location: 'Bodega Central Escalón',
    isService: false,
  },
  {
    id: 'prod_5',
    companyId: 'comp_1',
    code: 'SUP-ROLL-05',
    barcode: '7411000000057',
    name: 'Caja x 50 Rollos Papel Térmico DTE (80x70mm)',
    category: 'Suministros',
    unit: 'Caja',
    salePrice: 38.00,
    currentCost: 22.00,
    stock: 80,
    minStock: 20,
    location: 'Bodega Central Escalón',
    isService: false,
  },
  {
    id: 'prod_6',
    companyId: 'comp_1',
    code: 'BEV-COCA-06',
    barcode: '7411001001234',
    name: 'Coca-Cola 2.5L Retornable (Tienda)',
    category: 'Bebidas & Consumo',
    unit: 'Botella',
    salePrice: 1.85,
    currentCost: 1.40,
    stock: 120,
    minStock: 24,
    location: 'Estante Refrigerado A1',
    isService: false,
  },
  {
    id: 'prod_7',
    companyId: 'comp_1',
    code: 'BEV-AGUA-07',
    barcode: '7411002005678',
    name: 'Agua Purificada Cristal 600ml',
    category: 'Bebidas & Consumo',
    unit: 'Botella',
    salePrice: 0.65,
    currentCost: 0.38,
    stock: 240,
    minStock: 48,
    location: 'Estante Refrigerado A2',
    isService: false,
  },
  {
    id: 'prod_8',
    companyId: 'comp_1',
    code: 'SNK-CHIPS-08',
    barcode: '7411003009988',
    name: 'Snack Diana Quesitos 45g',
    category: 'Snacks & Abarrotes',
    unit: 'Bolsa',
    salePrice: 0.40,
    currentCost: 0.28,
    stock: 180,
    minStock: 30,
    location: 'Góndola Snacks',
    isService: false,
  },
];

export const SAMPLE_CUSTOMERS: Customer[] = [
  {
    id: 'cust_1',
    name: 'Innovaciones Digitales de El Salvador S.A. de C.V.',
    tradeName: 'InnovaDigital SV',
    nrc: '245678-9',
    nit: '0614-230918-103-2',
    giro: 'Comercio Electrónico y Soluciones de TI',
    address: 'Calle La Mascota #520, Col. San Benito, San Salvador',
    phone: '+503 2278-9900',
    email: 'compras@innovadigital.sv',
    isGranContribuyente: true,
    creditLimit: 5000.00,
    paymentTermDays: 30,
    ageRange: '26-35',
    gender: 'corporativo',
    acquisitionChannel: 'referido',
    department: 'San Salvador',
    municipality: 'San Salvador Centro (San Salvador, Mejicanos, Ayutuxtepeque, Cuscatancingo, Ciudad Delgado)',
    preferences: ['Facturación siempre con CCF DTE', 'Contacto por WhatsApp con Gerencia', 'Entregas en San Benito'],
    stage: 'vip',
    rating: 5,
    notesTimeline: [
      {
        id: 'cn_1',
        date: '2026-08-15',
        type: 'reunion',
        content: 'Reunión ejecutiva sobre renovación de licencias para 3 sucursales.',
        author: 'Lic. Carlos Henríquez',
      },
      {
        id: 'cn_2',
        date: '2026-08-02',
        type: 'whatsapp',
        content: 'Confirmaron recepción satisfactoria de los equipos POS DTE.',
        author: 'Sofía Palacios',
      },
    ],
  },
  {
    id: 'cust_2',
    name: 'Farmacias La Esperanza S.A. de C.V.',
    tradeName: 'Farmacias La Esperanza',
    nrc: '198765-4',
    nit: '0614-120515-101-8',
    giro: 'Comercialización de Medicamentos y Productos de Salud',
    address: 'Avenida España #312, Centro Histórico, San Salvador',
    phone: '+503 2222-4455',
    email: 'contabilidad@laesperanza.com.sv',
    isGranContribuyente: false,
    creditLimit: 3000.00,
    paymentTermDays: 15,
    ageRange: '36-50',
    gender: 'corporativo',
    acquisitionChannel: 'tienda_fisica',
    department: 'San Salvador',
    municipality: 'San Salvador Centro (San Salvador, Mejicanos, Ayutuxtepeque, Cuscatancingo, Ciudad Delgado)',
    preferences: ['Pagos quincenales', 'Pide rollos térmicos con frecuencia'],
    stage: 'frecuente',
    rating: 4,
    notesTimeline: [
      {
        id: 'cn_3',
        date: '2026-08-10',
        type: 'llamada',
        content: 'Solicitaron cotización para 4 lectores de barra QR adicionales.',
        author: 'Ing. Rodrigo Melgar',
      },
    ],
  },
  {
    id: 'cust_3',
    name: 'Andrea Michelle Guardado Portillo',
    tradeName: 'Boutique & Café Vainilla',
    nit: '0511-190392-102-3',
    dui: '04829104-5',
    nrc: '345129-8',
    giro: 'Venta de Ropa, Calzado y Cafetería',
    address: 'Centro Comercial Las Ramblas, Local 18, Santa Tecla',
    phone: '+503 7890-1234',
    email: 'andrea.guardado@gmail.com',
    isGranContribuyente: false,
    creditLimit: 1500.00,
    paymentTermDays: 30,
    ageRange: '26-35',
    gender: 'femenino',
    acquisitionChannel: 'instagram',
    department: 'La Libertad',
    municipality: 'La Libertad Centro (Santa Tecla, Antiguo Cuscatlán)',
    preferences: ['Atención directa por WhatsApp', 'Interesada en analítica de ventas por género'],
    stage: 'cotizacion',
    rating: 5,
    notesTimeline: [
      {
        id: 'cn_4',
        date: '2026-08-20',
        type: 'whatsapp',
        content: 'Pedido encargado: Terminal Touchscreen POS listo para entrega el jueves.',
        author: 'Licda. Brenda Marroquín',
      },
    ],
  },
  {
    id: 'cust_4',
    name: 'Roberto Ernesto Menjívar Alvarenga',
    tradeName: 'Taller & Repuestos Menjívar',
    nit: '0614-110885-101-7',
    dui: '02394811-9',
    giro: 'Mecánica Automotriz y Venta de Repuestos',
    address: '4a Calle Poniente #204, San Miguel',
    phone: '+503 7654-3210',
    email: 'tallermenjivar@outlook.com',
    isGranContribuyente: false,
    creditLimit: 800.00,
    paymentTermDays: 15,
    ageRange: '36-50',
    gender: 'masculino',
    acquisitionChannel: 'facebook',
    department: 'San Miguel',
    municipality: 'San Miguel Centro (San Miguel, Comacarán, Ullazapa)',
    preferences: ['Facturas Consumidor Final y CCF', 'Prefiere pagar por Transferencia Agrícola'],
    stage: 'primer_compra',
    rating: 4,
    notesTimeline: [
      {
        id: 'cn_5',
        date: '2026-08-18',
        type: 'llamada',
        content: 'Abono realizado con comprobante de transferencia bancaria.',
        author: 'Sofía Palacios',
      },
    ],
  },
  {
    id: 'cust_5',
    name: 'Gabriela María Zavaleta S.A. de C.V.',
    tradeName: 'Zavaleta & Asociados Abogados',
    nrc: '289104-2',
    nit: '0614-050417-104-9',
    giro: 'Servicios Jurídicos y Notariado',
    address: 'Colonia Médica, Pasaje 2 #114, San Salvador',
    phone: '+503 2260-1122',
    email: 'gzavaleta@zavaletalaw.com',
    isGranContribuyente: false,
    creditLimit: 2000.00,
    paymentTermDays: 30,
    ageRange: '50+',
    gender: 'femenino',
    acquisitionChannel: 'web',
    department: 'San Salvador',
    municipality: 'San Salvador Centro (San Salvador, Mejicanos, Ayutuxtepeque, Cuscatancingo, Ciudad Delgado)',
    preferences: ['Requiere reportes contables mensuales en PDF descargables'],
    stage: 'vip',
    rating: 5,
    notesTimeline: [
      {
        id: 'cn_6',
        date: '2026-08-12',
        type: 'reunion',
        content: 'Pidieron automatizar el envío de balances en PDF al final de mes.',
        author: 'Lic. Carlos Henríquez',
      },
    ],
  },
  {
    id: 'cust_6',
    name: 'Mateo Alejandro Benítez',
    tradeName: 'Studio Gamer & Streaming SV',
    nit: '0614-140201-106-8',
    dui: '06129841-2',
    giro: 'Producción Audiovisual y Streaming',
    address: 'Santa Ana Centro, Ave. Independencia #44',
    phone: '+503 7123-4567',
    email: 'mateo@gaminghub.sv',
    isGranContribuyente: false,
    creditLimit: 500.00,
    paymentTermDays: 0,
    ageRange: '18-25',
    gender: 'masculino',
    acquisitionChannel: 'instagram',
    department: 'Santa Ana',
    municipality: 'Santa Ana Centro (Santa Ana)',
    preferences: ['Compra siempre al contado', 'Usa Apple Pay / Tarjeta de Débito'],
    stage: 'cotizacion',
    rating: 5,
    notesTimeline: [
      {
        id: 'cn_7',
        date: '2026-08-22',
        type: 'whatsapp',
        content: 'Enviada cotización de software de facturación para creadores digitales.',
        author: 'Ing. Rodrigo Melgar',
      },
    ],
  },
  {
    id: 'cust_7',
    name: 'Valeria Nicole Campos Rivas',
    tradeName: 'Agencia de Marketing ViralSV',
    nit: '0614-290799-105-1',
    dui: '05928174-3',
    giro: 'Publicidad Digital y Manejo de Redes',
    address: 'Plaza Futura, Local 22, Col. Escalón, San Salvador',
    phone: '+503 7455-8899',
    email: 'valeria@viralsv.agency',
    isGranContribuyente: false,
    creditLimit: 1200.00,
    paymentTermDays: 15,
    ageRange: '26-35',
    gender: 'femenino',
    acquisitionChannel: 'whatsapp',
    department: 'San Salvador',
    municipality: 'San Salvador Centro (San Salvador, Mejicanos, Ayutuxtepeque, Cuscatancingo, Ciudad Delgado)',
    preferences: ['Cotizaciones por PDF directo a WhatsApp'],
    stage: 'prospecto',
    rating: 4,
    notesTimeline: [
      {
        id: 'cn_8',
        date: '2026-08-25',
        type: 'whatsapp',
        content: 'Prospecto nuevo captado por anuncio de WhatsApp. Interesada en módulo de Planilla SV.',
        author: 'Sofía Palacios',
      },
    ],
  },
];

export const SAMPLE_SUPPLIERS: Supplier[] = [
  {
    id: 'supp_1',
    name: 'Importadora Tecnológica Global S.A. de C.V.',
    tradeName: 'TechGlobal SV',
    nrc: '154320-1',
    nit: '0614-100412-101-5',
    giro: 'Importación y Venta Mayorista de Equipos Electrónicos y Servidores',
    address: 'Boulevard Constitución #400, San Salvador',
    phone: '+503 2233-5500',
    email: 'pedidos@techglobalsv.com',
    isGranContribuyente: true,
    isSujetoExcluido: false,
    paymentTermDays: 30,
    category: 'Tecnología & Hardware',
    leadTimeDays: 3,
    rating: 5,
    qualityScore: 5,
    timelinessScore: 5,
    pricingScore: 4,
    suppliedProducts: ['Terminales POS', 'Lectores de Código', 'Impresoras Térmicas'],
    notesTimeline: [
      {
        id: 'sn_1',
        date: '2026-08-01',
        type: 'negociacion',
        content: 'Acuerdo de 5% de descuento por volumen en lotes de 20 unidades.',
        author: 'Ing. Rodrigo Melgar',
      },
    ],
  },
  {
    id: 'supp_2',
    name: 'Papelería e Impresos de Centroamérica S.A. de C.V.',
    tradeName: 'PapelCentro SV',
    nrc: '201948-7',
    nit: '0614-080316-102-9',
    giro: 'Fabricación y Comercialización de Formatos Continuos y Rollos Térmicos',
    address: 'Zona Industrial Plan de La Laguna, Antiguo Cuscatlán',
    phone: '+503 2243-7788',
    email: 'ventas@papelcentrosv.com',
    isGranContribuyente: false,
    isSujetoExcluido: false,
    paymentTermDays: 15,
    category: 'Empaque & Suministros',
    leadTimeDays: 2,
    rating: 4,
    qualityScore: 4,
    timelinessScore: 5,
    pricingScore: 5,
    suppliedProducts: ['Rollos Térmicos 80mm', 'Etiquetas Adhesivas'],
    notesTimeline: [
      {
        id: 'sn_2',
        date: '2026-07-20',
        type: 'acuerdo_credito',
        content: 'Límite de crédito extendido a $2,500 a 15 días plazo.',
        author: 'Licda. Brenda Marroquín',
      },
    ],
  },
  {
    id: 'supp_3',
    name: 'Lic. Mauricio Alexander Ramos (Consultor Legal)',
    tradeName: 'Ramos & Asociados Consultoría',
    nrc: '',
    nit: '0614-190678-101-2',
    giro: 'Servicios de Asesoría Legal Corporativa y Notariado',
    address: 'Colonia San Francisco, Calle Los Abetos #18, San Salvador',
    phone: '+503 7744-1122',
    email: 'mramos.abogado@gmail.com',
    isGranContribuyente: false,
    isSujetoExcluido: true, // Sujeto Excluido -> Retención 10% Renta
    paymentTermDays: 0,
    category: 'Servicios Profesionales',
    leadTimeDays: 1,
    rating: 5,
    qualityScore: 5,
    timelinessScore: 4,
    pricingScore: 4,
    suppliedProducts: ['Asesoría Legal DTE', 'Contratos de Trabajo'],
    notesTimeline: [
      {
        id: 'sn_3',
        date: '2026-08-14',
        type: 'visita',
        content: 'Revisión y actualización del reglamento interno de trabajo.',
        author: 'Lic. Carlos Henríquez',
      },
    ],
  },
  {
    id: 'supp_4',
    name: 'Servicios de Nube y Conectividad SV S.A.',
    tradeName: 'CloudSV Datacenter',
    nrc: '267891-3',
    nit: '0614-021119-103-8',
    giro: 'Servicios de Hospedaje Web, Servidores Dedicados e Infraestructura Cloud',
    address: 'World Trade Center, Torre 2, San Salvador',
    phone: '+503 2209-3000',
    email: 'billing@cloudsv.com',
    isGranContribuyente: true,
    isSujetoExcluido: false,
    paymentTermDays: 30,
    category: 'Infraestructura Cloud',
    leadTimeDays: 1,
    rating: 5,
    qualityScore: 5,
    timelinessScore: 5,
    pricingScore: 4,
    suppliedProducts: ['Servidores Cloud', 'Certificados SSL', 'Backups Automáticos'],
    notesTimeline: [
      {
        id: 'sn_4',
        date: '2026-08-05',
        type: 'negociacion',
        content: 'Contrato de redundancia y 99.9% uptime renovado.',
        author: 'Ing. Rodrigo Melgar',
      },
    ],
  },
];

export const SAMPLE_EMPLOYEES: Employee[] = [
  {
    id: 'emp_1',
    companyId: 'comp_1',
    code: 'EMP-001',
    firstName: 'Guillermo Antonio',
    lastName: 'Castillo Pineda',
    dui: '03492817-4',
    nit: '0614-150790-102-1',
    isssNumber: '109283746',
    afpNumber: '293847561029',
    afpName: 'Crecer',
    position: 'Arquitecto de Software Full Stack',
    department: 'Tecnología & Desarrollo',
    baseSalary: 1600.00,
    contractType: 'permanente',
    hireDate: '2023-02-01',
    bankName: 'Banco Agrícola',
    bankAccountNumber: '300-192847-2',
    isActive: true,
    rating: 5,
    evaluations: [
      {
        id: 'eval_1',
        date: '2026-06-30',
        score: 5,
        productivity: 5,
        punctuality: 5,
        teamwork: 5,
        feedback: 'Excelente desempeño en el despliegue del motor DTE para Hacienda.',
        evaluator: 'Ing. Rodrigo Melgar',
      },
    ],
  },
  {
    id: 'emp_2',
    companyId: 'comp_1',
    code: 'EMP-002',
    firstName: 'Claudia Elizabeth',
    lastName: 'Morales Rivas',
    dui: '04819283-8',
    nit: '0511-220395-101-7',
    isssNumber: '119283745',
    afpNumber: '394857610293',
    afpName: 'Confía',
    position: 'Especialista en Soporte & Éxito del Cliente',
    department: 'Atención al Cliente',
    baseSalary: 750.00,
    contractType: 'permanente',
    hireDate: '2024-05-15',
    bankName: 'BAC Credomatic',
    bankAccountNumber: '109-283746-1',
    isActive: true,
    rating: 4.8,
    evaluations: [
      {
        id: 'eval_2',
        date: '2026-06-30',
        score: 4.8,
        productivity: 4.8,
        punctuality: 5,
        teamwork: 4.7,
        feedback: 'Gran empatía con los clientes en la inducción al módulo de facturación.',
        evaluator: 'Lic. Carlos Henríquez',
      },
    ],
  },
  {
    id: 'emp_3',
    companyId: 'comp_1',
    code: 'EMP-003',
    firstName: 'José Mario',
    lastName: 'López Hernández',
    dui: '02948571-0',
    nit: '0614-041088-103-6',
    isssNumber: '129384756',
    afpNumber: '495867102938',
    afpName: 'Crecer',
    position: 'Ejecutivo Comercial & Alianzas Estratégicas',
    department: 'Ventas & Mercadeo',
    baseSalary: 900.00,
    contractType: 'permanente',
    hireDate: '2023-11-01',
    bankName: 'Banco Cuscatlán',
    bankAccountNumber: '028-394857-4',
    isActive: true,
    rating: 4.5,
    evaluations: [
      {
        id: 'eval_3',
        date: '2026-06-30',
        score: 4.5,
        productivity: 4.5,
        punctuality: 4.3,
        teamwork: 4.8,
        feedback: 'Superó la cuota mensual de captación de pequeñas empresas en Santa Tecla.',
        evaluator: 'Lic. Carlos Henríquez',
      },
    ],
  },
  {
    id: 'emp_4',
    companyId: 'comp_1',
    code: 'EMP-004',
    firstName: 'Adriana Marcela',
    lastName: 'Flores Quintanilla',
    dui: '05192847-3',
    nit: '0614-301298-104-2',
    isssNumber: '139485767',
    afpNumber: '596878103948',
    afpName: 'Confía',
    position: 'Asistente Contable & Facturación',
    department: 'Finanzas & Contabilidad',
    baseSalary: 600.00,
    contractType: 'permanente',
    hireDate: '2025-01-10',
    bankName: 'Banco Agrícola',
    bankAccountNumber: '310-928374-5',
    isActive: true,
    rating: 4.9,
    evaluations: [
      {
        id: 'eval_4',
        date: '2026-06-30',
        score: 4.9,
        productivity: 5,
        punctuality: 4.8,
        teamwork: 5,
        feedback: 'Mantiene las conciliaciones bancarias al día y control de correlativos DTE.',
        evaluator: 'Licda. Brenda Marroquín',
      },
    ],
  },
];

export const SAMPLE_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: 'bank_1',
    companyId: 'comp_1',
    accountName: 'Banco Agrícola - Operaciones Principales',
    bankName: 'Banco Agrícola',
    accountNumber: '300-482910-4',
    accountType: 'banco_corriente',
    accountingCode: '1101-03',
    initialBalance: 15000.00,
    currentBalance: 18450.00,
    currency: 'USD',
  },
  {
    id: 'bank_2',
    companyId: 'comp_1',
    accountName: 'BAC Credomatic - Recaudación & Pasarela',
    bankName: 'BAC Credomatic',
    accountNumber: '109-384756-2',
    accountType: 'banco_corriente',
    accountingCode: '1101-04',
    initialBalance: 8000.00,
    currentBalance: 9800.00,
    currency: 'USD',
  },
  {
    id: 'bank_3',
    companyId: 'comp_1',
    accountName: 'Caja General Oficina Central',
    bankName: 'Efectivo en Bóveda',
    accountNumber: 'CJ-01',
    accountType: 'caja_general',
    accountingCode: '1101-01',
    initialBalance: 1500.00,
    currentBalance: 2450.00,
    currency: 'USD',
  },
  {
    id: 'bank_4',
    companyId: 'comp_1',
    accountName: 'Caja Chica Gastos Menores',
    bankName: 'Efectivo',
    accountNumber: 'CC-01',
    accountType: 'caja_chica',
    accountingCode: '1101-02',
    initialBalance: 300.00,
    currentBalance: 300.00,
    currency: 'USD',
  },
];

export const SAMPLE_INVOICES: Invoice[] = [
  {
    id: 'inv_1',
    companyId: 'comp_1',
    branchId: 'branch_1',
    branchName: 'Casa Matriz - Escalón',
    type: 'credito_fiscal',
    correlativeNumber: 'CCF-000101',
    dteCode: 'DTE-03-M001P001-000000000000101',
    controlNumber: 'DTE-03-000101-2026',
    date: '2026-08-05',
    dueDate: '2026-09-04',
    customerId: 'cust_1',
    customerName: 'Innovaciones Digitales de El Salvador S.A. de C.V.',
    customerNrc: '245678-9',
    customerNit: '0614-230918-103-2',
    customerIsGranContribuyente: true,
    paymentCondition: 'credito_30',
    status: 'pagada',
    items: [
      {
        id: 'item_1',
        productId: 'prod_1',
        productCode: 'SRV-ERP-01',
        description: 'Licencia FinaPyme ERP Anual (Cloud SaaS)',
        quantity: 2,
        unitPrice: 1200.00,
        unitCost: 350.00,
        total: 2400.00,
      },
      {
        id: 'item_2',
        productId: 'prod_3',
        productCode: 'HW-POS-03',
        description: 'Terminal Touchscreen POS DTE + Impresora Térmica 80mm',
        quantity: 2,
        unitPrice: 480.00,
        unitCost: 310.00,
        total: 960.00,
      },
    ],
    sumasGravadas: 3360.00,
    sumasExentas: 0.00,
    sumasNoSujetas: 0.00,
    iva13: 436.80,
    ivaRetenido1: 0.00, // Emisor es Gran Contribuyente
    ivaPercibido1: 0.00,
    totalPagar: 3796.80,
    saldoPendiente: 0.00,
    createdAt: '2026-08-05T10:30:00Z',
  },
  {
    id: 'inv_2',
    companyId: 'comp_1',
    branchId: 'branch_1',
    branchName: 'Casa Matriz - Escalón',
    type: 'credito_fiscal',
    correlativeNumber: 'CCF-000102',
    dteCode: 'DTE-03-M001P001-000000000000102',
    controlNumber: 'DTE-03-000102-2026',
    date: '2026-08-12',
    dueDate: '2026-08-27',
    customerId: 'cust_2',
    customerName: 'Farmacias La Esperanza S.A. de C.V.',
    customerNrc: '198765-4',
    customerNit: '0614-120515-101-8',
    customerIsGranContribuyente: false,
    paymentCondition: 'credito_15',
    status: 'emitida',
    items: [
      {
        id: 'item_3',
        productId: 'prod_4',
        productCode: 'HW-SCAN-04',
        description: 'Lector Láser de Código de Barras y QR 2D',
        quantity: 4,
        unitPrice: 75.00,
        unitCost: 42.00,
        total: 300.00,
      },
      {
        id: 'item_4',
        productId: 'prod_5',
        productCode: 'SUP-ROLL-05',
        description: 'Caja x 50 Rollos Papel Térmico DTE (80x70mm)',
        quantity: 10,
        unitPrice: 38.00,
        unitCost: 22.00,
        total: 380.00,
      },
    ],
    sumasGravadas: 680.00,
    sumasExentas: 0.00,
    sumasNoSujetas: 0.00,
    iva13: 88.40,
    ivaRetenido1: 0.00,
    ivaPercibido1: 6.80, // Emisor es GC y cliente no lo es -> Percepción 1%
    totalPagar: 775.20,
    saldoPendiente: 775.20,
    createdAt: '2026-08-12T14:15:00Z',
  },
  {
    id: 'inv_3',
    companyId: 'comp_1',
    branchId: 'branch_2',
    branchName: 'Sucursal Santa Tecla',
    type: 'factura_consumidor_final',
    correlativeNumber: 'FCF-000201',
    dteCode: 'DTE-01-M001P001-000000000000201',
    controlNumber: 'DTE-01-000201-2026',
    date: '2026-08-18',
    dueDate: '2026-08-18',
    customerId: 'cust_3',
    customerName: 'Andrea Michelle Guardado Portillo',
    customerNit: '0511-190392-102-3',
    customerIsGranContribuyente: false,
    paymentCondition: 'contado',
    status: 'pagada',
    items: [
      {
        id: 'item_5',
        productId: 'prod_3',
        productCode: 'HW-POS-03',
        description: 'Terminal Touchscreen POS DTE + Impresora Térmica 80mm',
        quantity: 1,
        unitPrice: 480.00,
        unitCost: 310.00,
        total: 480.00,
      },
    ],
    sumasGravadas: 480.00,
    sumasExentas: 0.00,
    sumasNoSujetas: 0.00,
    iva13: 62.40,
    ivaRetenido1: 0.00,
    ivaPercibido1: 0.00,
    totalPagar: 542.40,
    saldoPendiente: 0.00,
    createdAt: '2026-08-18T16:00:00Z',
  },
  {
    id: 'inv_4',
    companyId: 'comp_1',
    branchId: 'branch_3',
    branchName: 'Sucursal San Miguel',
    type: 'credito_fiscal',
    correlativeNumber: 'CCF-000103',
    dteCode: 'DTE-03-M001P001-000000000000103',
    controlNumber: 'DTE-03-000103-2026',
    date: '2026-08-21',
    dueDate: '2026-09-20',
    customerId: 'cust_5',
    customerName: 'Gabriela María Zavaleta S.A. de C.V.',
    customerNrc: '289104-2',
    customerNit: '0614-050417-104-9',
    customerIsGranContribuyente: false,
    paymentCondition: 'credito_30',
    status: 'emitida',
    items: [
      {
        id: 'item_6',
        productId: 'prod_1',
        productCode: 'SRV-ERP-01',
        description: 'Licencia FinaPyme ERP Anual (Cloud SaaS)',
        quantity: 1,
        unitPrice: 1200.00,
        unitCost: 350.00,
        total: 1200.00,
      },
      {
        id: 'item_7',
        productId: 'prod_2',
        productCode: 'SRV-CONS-02',
        description: 'Consultoría e Implementación NIIF / DTE MH',
        quantity: 5,
        unitPrice: 85.00,
        unitCost: 35.00,
        total: 425.00,
      },
    ],
    sumasGravadas: 1625.00,
    sumasExentas: 0.00,
    sumasNoSujetas: 0.00,
    iva13: 211.25,
    ivaRetenido1: 0.00,
    ivaPercibido1: 16.25,
    totalPagar: 1852.50,
    saldoPendiente: 1852.50,
    createdAt: '2026-08-21T11:45:00Z',
  },
];

export const SAMPLE_PURCHASES: Purchase[] = [
  {
    id: 'pur_1',
    companyId: 'comp_1',
    branchId: 'branch_1',
    branchName: 'Casa Matriz - Escalón',
    docType: 'ccf_compra',
    documentNumber: 'CCF-49201',
    date: '2026-08-03',
    dueDate: '2026-09-02',
    supplierId: 'supp_1',
    supplierName: 'Importadora Tecnológica Global S.A. de C.V.',
    supplierNrc: '154320-1',
    supplierNit: '0614-100412-101-5',
    supplierIsGranContribuyente: true,
    status: 'pagada',
    items: [
      {
        id: 'pitem_1',
        productId: 'prod_3',
        description: 'Terminal Touchscreen POS DTE',
        quantity: 10,
        unitCost: 310.00,
        total: 3100.00,
      },
      {
        id: 'pitem_2',
        productId: 'prod_4',
        description: 'Lector Láser de Código de Barras y QR 2D',
        quantity: 20,
        unitCost: 42.00,
        total: 840.00,
      },
    ],
    comprasGravadas: 3940.00,
    comprasExentas: 0.00,
    comprasSujetoExcluido: 0.00,
    ivaCreditoFiscal: 512.20,
    retencionRenta10: 0.00,
    retencionIva1: 0.00,
    percepcionIva1: 0.00,
    totalPagar: 4452.20,
    saldoPendiente: 0.00,
    createdAt: '2026-08-03T09:00:00Z',
  },
  {
    id: 'pur_2',
    companyId: 'comp_1',
    docType: 'factura_sujeto_excluido',
    documentNumber: 'FSE-0012',
    date: '2026-08-14',
    dueDate: '2026-08-14',
    supplierId: 'supp_3',
    supplierName: 'Lic. Mauricio Alexander Ramos (Consultor Legal)',
    supplierNrc: '',
    supplierNit: '0614-190678-101-2',
    supplierIsGranContribuyente: false,
    status: 'pagada',
    items: [
      {
        id: 'pitem_3',
        productId: 'prod_2',
        description: 'Servicios de Asesoría Legal Corporativa y Notariado',
        quantity: 1,
        unitCost: 500.00,
        total: 500.00,
      },
    ],
    comprasGravadas: 0.00,
    comprasExentas: 0.00,
    comprasSujetoExcluido: 500.00,
    ivaCreditoFiscal: 0.00,
    retencionRenta10: 50.00, // Retención 10% Renta por Sujeto Excluido
    retencionIva1: 0.00,
    percepcionIva1: 0.00,
    totalPagar: 450.00, // Líquido pagado al profesional
    saldoPendiente: 0.00,
    createdAt: '2026-08-14T15:30:00Z',
  },
  {
    id: 'pur_3',
    companyId: 'comp_1',
    docType: 'ccf_compra',
    documentNumber: 'CCF-88219',
    date: '2026-08-19',
    dueDate: '2026-09-03',
    supplierId: 'supp_2',
    supplierName: 'Papelería e Impresos de Centroamérica S.A. de C.V.',
    supplierNrc: '201948-7',
    supplierNit: '0614-080316-102-9',
    supplierIsGranContribuyente: false,
    status: 'registrada',
    items: [
      {
        id: 'pitem_4',
        productId: 'prod_5',
        description: 'Caja x 50 Rollos Papel Térmico DTE (80x70mm)',
        quantity: 50,
        unitCost: 22.00,
        total: 1100.00,
      },
    ],
    comprasGravadas: 1100.00,
    comprasExentas: 0.00,
    comprasSujetoExcluido: 0.00,
    ivaCreditoFiscal: 143.00,
    retencionRenta10: 0.00,
    retencionIva1: 11.00, // Retenemos 1% porque somos Gran Contribuyente
    percepcionIva1: 0.00,
    totalPagar: 1232.00,
    saldoPendiente: 1232.00,
    createdAt: '2026-08-19T11:00:00Z',
  },
];

export const SAMPLE_KARDEX_MOVEMENTS: KardexMovement[] = [
  {
    id: 'kdx_1',
    companyId: 'comp_1',
    productId: 'prod_3',
    productName: 'Terminal Touchscreen POS DTE + Impresora Térmica 80mm',
    date: '2026-08-01',
    type: 'ajuste_positivo',
    referenceDoc: 'INVENTARIO-INICIAL-2026',
    quantity: 16,
    unitCost: 310.00,
    totalCost: 4960.00,
    balanceQuantity: 16,
    balanceUnitCost: 310.00,
    balanceTotalCost: 4960.00,
    notes: 'Saldo inicial de apertura de ejercicio',
  },
  {
    id: 'kdx_2',
    companyId: 'comp_1',
    productId: 'prod_3',
    productName: 'Terminal Touchscreen POS DTE + Impresora Térmica 80mm',
    date: '2026-08-03',
    type: 'entrada_compra',
    referenceDoc: 'CCF-49201 (TechGlobal)',
    quantity: 10,
    unitCost: 310.00,
    totalCost: 3100.00,
    balanceQuantity: 26,
    balanceUnitCost: 310.00,
    balanceTotalCost: 8060.00,
    notes: 'Compra de lote para stock de contingencia',
  },
  {
    id: 'kdx_3',
    companyId: 'comp_1',
    productId: 'prod_3',
    productName: 'Terminal Touchscreen POS DTE + Impresora Térmica 80mm',
    date: '2026-08-05',
    type: 'salida_venta',
    referenceDoc: 'CCF-000101 (InnovaDigital)',
    quantity: 2,
    unitCost: 310.00,
    totalCost: 620.00,
    balanceQuantity: 24,
    balanceUnitCost: 310.00,
    balanceTotalCost: 7440.00,
    notes: 'Venta facturada',
  },
];

export const INITIAL_DYNAMIC_WIDGETS: DynamicChartWidget[] = [
  {
    id: 'dw_age',
    title: 'Ventas por Segmento de Edad',
    description: 'Distribución de facturación según el rango de edad de clientes.',
    chartType: 'bar',
    data: [
      { name: '18-25 años', value: 850, secondaryValue: 2 },
      { name: '26-35 años', value: 4339, secondaryValue: 2 },
      { name: '36-50 años', value: 775, secondaryValue: 1 },
      { name: '50+ años', value: 1852, secondaryValue: 1 },
    ],
    insights: [
      'El segmento de 26 a 35 años representa el 55.5% del volumen de ventas total.',
      'El ticket promedio más alto se registra en clientes mayores de 50 años ($1,852.50).',
    ],
    createdAt: '2026-08-20T10:00:00Z',
    createdByAI: false,
  },
  {
    id: 'dw_gender',
    title: 'Ventas por Género / Tipo de Cliente',
    description: 'Participación en ventas por género y cuentas corporativas.',
    chartType: 'pie',
    data: [
      { name: 'Corporativo (Empresas)', value: 4572, color: '#4f46e5' },
      { name: 'Femenino', value: 2394, color: '#ec4899' },
      { name: 'Masculino', value: 850, color: '#06b6d4' },
    ],
    insights: [
      'Las cuentas corporativas B2B generan el 58.5% de los ingresos totales.',
      'El segmento femenino muestra una tasa de fidelización 30% superior en compras recurrentes.',
    ],
    createdAt: '2026-08-21T14:00:00Z',
    createdByAI: false,
  },
  {
    id: 'dw_dept',
    title: 'Ventas por Departamento (El Salvador)',
    description: 'Facturación regionalizada en los 14 departamentos de El Salvador.',
    chartType: 'bar',
    data: [
      { name: 'San Salvador', value: 6424 },
      { name: 'La Libertad', value: 542 },
      { name: 'San Miguel', value: 0 },
      { name: 'Santa Ana', value: 850 },
    ],
    insights: [
      'San Salvador concentra el 82.2% de las transacciones activas.',
      'Oportunidad de expansión comercial en la zona oriental (San Miguel y Usulután).',
    ],
    createdAt: '2026-08-22T09:30:00Z',
    createdByAI: false,
  },
  {
    id: 'dw_channel',
    title: 'Ventas por Canal de Captación',
    description: 'Rendimiento de canales comerciales y redes sociales en El Salvador.',
    chartType: 'area',
    data: [
      { name: 'Referidos / Boca a Boca', value: 3796 },
      { name: 'Web Directa', value: 1852 },
      { name: 'Instagram Ads', value: 1392 },
      { name: 'Tienda Física', value: 775 },
    ],
    insights: [
      'Los referidos son el canal de menor costo de adquisición y mayor conversión.',
      'Instagram Ads lidera la captación en microempresas y comercios minoristas.',
    ],
    createdAt: '2026-08-23T11:00:00Z',
    createdByAI: false,
  },
];

export const SAMPLE_PAYROLLS: Payroll[] = [
  {
    id: 'pay_sample_1',
    companyId: 'comp_1',
    periodNumber: 1,
    periodType: 'mensual',
    year: 2026,
    month: 8,
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    paymentDate: '2026-08-30',
    status: 'aprobada',
    details: [
      {
        employeeId: 'emp_1',
        employeeName: 'Guillermo Antonio Castillo Pineda',
        dui: '03492817-4',
        position: 'Arquitecto de Software Full Stack',
        baseSalary: 1600.00,
        overtimePay: 0,
        bonuses: 0,
        otherIncome: 0,
        totalDevengado: 1600.00,
        isssLaboral: 30.00,
        afpLaboral: 116.00,
        baseImponibleRenta: 1454.00,
        rentaRetencion: 171.75,
        otherDeductions: 0,
        totalDeducciones: 317.75,
        liquidoPagar: 1282.25,
        isssPatronal: 75.00,
        afpPatronal: 140.00,
        insaforpPatronal: 16.00,
        provisionAguinaldo: 66.72,
        provisionVacacion: 86.72,
        provisionIndemnizacion: 133.28,
      },
      {
        employeeId: 'emp_2',
        employeeName: 'Claudia Elizabeth Morales Rivas',
        dui: '04819283-8',
        position: 'Especialista en Soporte & Éxito del Cliente',
        baseSalary: 750.00,
        overtimePay: 0,
        bonuses: 0,
        otherIncome: 0,
        totalDevengado: 750.00,
        isssLaboral: 22.50,
        afpLaboral: 54.38,
        baseImponibleRenta: 673.12,
        rentaRetencion: 37.78,
        otherDeductions: 0,
        totalDeducciones: 114.66,
        liquidoPagar: 635.34,
        isssPatronal: 56.25,
        afpPatronal: 65.63,
        insaforpPatronal: 7.50,
        provisionAguinaldo: 31.28,
        provisionVacacion: 40.65,
        provisionIndemnizacion: 62.48,
      },
      {
        employeeId: 'emp_3',
        employeeName: 'José Mario López Hernández',
        dui: '02948571-0',
        position: 'Ejecutivo Comercial & Alianzas Estratégicas',
        baseSalary: 900.00,
        overtimePay: 0,
        bonuses: 0,
        otherIncome: 0,
        totalDevengado: 900.00,
        isssLaboral: 27.00,
        afpLaboral: 65.25,
        baseImponibleRenta: 807.75,
        rentaRetencion: 51.25,
        otherDeductions: 0,
        totalDeducciones: 143.50,
        liquidoPagar: 756.50,
        isssPatronal: 67.50,
        afpPatronal: 78.75,
        insaforpPatronal: 9.00,
        provisionAguinaldo: 37.53,
        provisionVacacion: 48.78,
        provisionIndemnizacion: 74.97,
      },
      {
        employeeId: 'emp_4',
        employeeName: 'Adriana Marcela Flores Quintanilla',
        dui: '05192847-3',
        position: 'Asistente Contable & Facturación',
        baseSalary: 600.00,
        overtimePay: 0,
        bonuses: 0,
        otherIncome: 0,
        totalDevengado: 600.00,
        isssLaboral: 18.00,
        afpLaboral: 43.50,
        baseImponibleRenta: 538.50,
        rentaRetencion: 24.32,
        otherDeductions: 0,
        totalDeducciones: 85.82,
        liquidoPagar: 514.18,
        isssPatronal: 45.00,
        afpPatronal: 52.50,
        insaforpPatronal: 6.00,
        provisionAguinaldo: 25.02,
        provisionVacacion: 32.52,
        provisionIndemnizacion: 49.98,
      },
    ],
    totalDevengado: 3850.00,
    totalIsssLaboral: 97.50,
    totalAfpLaboral: 279.13,
    totalRentaRetenida: 285.10,
    totalLiquido: 3188.27,
    totalIsssPatronal: 243.75,
    totalAfpPatronal: 336.88,
    totalInsaforpPatronal: 38.50,
    totalProvisiones: 689.93,
    costoTotalEmpresa: 5159.06,
    accountingEntryId: 'asiento_pay_01',
    createdAt: '2026-08-01T08:00:00Z',
  },
];

export const SAMPLE_JOURNAL_ENTRIES: JournalEntry[] = [
  {
    id: 'asiento_apertura_2026',
    companyId: 'comp_1',
    entryNumber: 1,
    date: '2026-01-02',
    concept: 'Asiento de Apertura de Ejercicio Fiscal 2026 - Saldos Iniciales NIIF para PYMES',
    sourceModule: 'manual',
    status: 'asentada',
    totalDebit: 55000.00,
    totalCredit: 55000.00,
    isBalanced: true,
    createdAt: '2026-01-02T08:00:00Z',
    lines: [
      {
        accountCode: '1101-03',
        accountName: 'Banco Agrícola - Operaciones Principales',
        debit: 15000.00,
        credit: 0,
        concept: 'Disponibilidad en cuenta corriente',
      },
      {
        accountCode: '1101-04',
        accountName: 'BAC Credomatic - Recaudación & Pasarela',
        debit: 8000.00,
        credit: 0,
        concept: 'Disponibilidad en cuenta recaudadora',
      },
      {
        accountCode: '1101-01',
        accountName: 'Caja General Oficina Central',
        debit: 1500.00,
        credit: 0,
        concept: 'Efectivo en caja general',
      },
      {
        accountCode: '1101-02',
        accountName: 'Caja Chica Gastos Menores',
        debit: 300.00,
        credit: 0,
        concept: 'Fondo fijo de caja chica',
      },
      {
        accountCode: '1103-01',
        accountName: 'Cuentas por Cobrar Comerciales',
        debit: 5200.00,
        credit: 0,
        concept: 'Saldo de clientes de ejercicio anterior',
      },
      {
        accountCode: '1105-01',
        accountName: 'Mercaderías para la Venta (Bodega Central)',
        debit: 10000.00,
        credit: 0,
        concept: 'Inventario inicial valorado al costo promedio',
      },
      {
        accountCode: '1201-01',
        accountName: 'Mobiliario, Equipo y Servidores',
        debit: 15000.00,
        credit: 0,
        concept: 'Activos fijos tangibles de computación y oficina',
      },
      {
        accountCode: '2101-01',
        accountName: 'Proveedores Locales (CxP)',
        debit: 0,
        credit: 5000.00,
        concept: 'Obligaciones comerciales por pagar',
      },
      {
        accountCode: '3101-01',
        accountName: 'Capital Social Pagado',
        debit: 0,
        credit: 40000.00,
        concept: 'Aporte de accionistas s/g Escritura de Constitución',
      },
      {
        accountCode: '3103-01',
        accountName: 'Resultados Acumulados de Ejercicios Anteriores',
        debit: 0,
        credit: 10000.00,
        concept: 'Utilidades retenidas acumuladas',
      },
    ],
  },
  {
    id: 'asiento_inv_1',
    companyId: 'comp_1',
    entryNumber: 2,
    date: '2026-08-05',
    concept: 'Venta s/g CCF N° CCF-000101 a Innovaciones Digitales de El Salvador S.A. de C.V.',
    sourceModule: 'ventas',
    referenceDoc: 'CCF-000101',
    status: 'asentada',
    totalDebit: 4416.80,
    totalCredit: 4416.80,
    isBalanced: true,
    createdAt: '2026-08-05T10:30:00Z',
    lines: [
      {
        accountCode: '1101-03',
        accountName: 'Banco Agrícola - Operaciones Principales',
        debit: 3796.80,
        credit: 0,
        concept: 'Cobro de venta CCF-000101',
      },
      {
        accountCode: '5101',
        accountName: 'Ingresos por Ventas Locales Gravadas',
        debit: 0,
        credit: 3360.00,
        concept: 'Venta neta gravada',
      },
      {
        accountCode: '2107-01',
        accountName: 'IVA Débito Fiscal (Ventas Locales)',
        debit: 0,
        credit: 436.80,
        concept: 'Débito Fiscal 13% s/g CCF-000101',
      },
      {
        accountCode: '4101',
        accountName: 'Costo de Ventas (Mercaderías)',
        debit: 620.00,
        credit: 0,
        concept: 'Costo de hardware POS entregado',
      },
      {
        accountCode: '1105-01',
        accountName: 'Mercaderías para la Venta (Bodega Central)',
        debit: 0,
        credit: 620.00,
        concept: 'Salida de bodega por venta',
      },
    ],
  },
  {
    id: 'asiento_inv_2',
    companyId: 'comp_1',
    entryNumber: 3,
    date: '2026-08-12',
    concept: 'Venta s/g CCF N° CCF-000102 a Farmacias La Esperanza S.A. de C.V.',
    sourceModule: 'ventas',
    referenceDoc: 'CCF-000102',
    status: 'asentada',
    totalDebit: 1163.20,
    totalCredit: 1163.20,
    isBalanced: true,
    createdAt: '2026-08-12T14:15:00Z',
    lines: [
      {
        accountCode: '1103-01',
        accountName: 'Clientes Locales (CxC)',
        debit: 775.20,
        credit: 0,
        concept: 'Cuenta por cobrar a Farmacias La Esperanza (Crédito 15 días)',
      },
      {
        accountCode: '5101',
        accountName: 'Ingresos por Ventas Locales Gravadas',
        debit: 0,
        credit: 680.00,
        concept: 'Venta neta gravada CCF-000102',
      },
      {
        accountCode: '2107-01',
        accountName: 'IVA Débito Fiscal (Ventas Locales)',
        debit: 0,
        credit: 88.40,
        concept: 'Débito fiscal 13% CCF-000102',
      },
      {
        accountCode: '2107-02',
        accountName: 'IVA Percibido 1%',
        debit: 0,
        credit: 6.80,
        concept: 'Percepción 1% aplicada al cliente',
      },
      {
        accountCode: '4101',
        accountName: 'Costo de Ventas (Mercaderías)',
        debit: 388.00,
        credit: 0,
        concept: 'Costo de lectores y rollos entregados',
      },
      {
        accountCode: '1105-01',
        accountName: 'Mercaderías para la Venta (Bodega Central)',
        debit: 0,
        credit: 388.00,
        concept: 'Descargo de inventario por venta',
      },
    ],
  },
  {
    id: 'asiento_inv_3',
    companyId: 'comp_1',
    entryNumber: 4,
    date: '2026-08-18',
    concept: 'Venta s/g FCF N° FCF-000201 a Andrea Michelle Guardado Portillo',
    sourceModule: 'ventas',
    referenceDoc: 'FCF-000201',
    status: 'asentada',
    totalDebit: 852.40,
    totalCredit: 852.40,
    isBalanced: true,
    createdAt: '2026-08-18T16:00:00Z',
    lines: [
      {
        accountCode: '1101-01',
        accountName: 'Caja General Oficina Central',
        debit: 542.40,
        credit: 0,
        concept: 'Cobro de venta de contado en caja',
      },
      {
        accountCode: '5101',
        accountName: 'Ingresos por Ventas Locales Gravadas',
        debit: 0,
        credit: 480.00,
        concept: 'Venta neta consumidor final',
      },
      {
        accountCode: '2107-01',
        accountName: 'IVA Débito Fiscal (Ventas Locales)',
        debit: 0,
        credit: 62.40,
        concept: 'Débito Fiscal 13% FCF-000201',
      },
      {
        accountCode: '4101',
        accountName: 'Costo de Ventas (Mercaderías)',
        debit: 310.00,
        credit: 0,
        concept: 'Costo de terminal POS vendida',
      },
      {
        accountCode: '1105-01',
        accountName: 'Mercaderías para la Venta (Bodega Central)',
        debit: 0,
        credit: 310.00,
        concept: 'Descargo de inventario',
      },
    ],
  },
  {
    id: 'asiento_inv_4',
    companyId: 'comp_1',
    entryNumber: 5,
    date: '2026-08-21',
    concept: 'Venta s/g CCF N° CCF-000103 a Gabriela María Zavaleta S.A. de C.V.',
    sourceModule: 'ventas',
    referenceDoc: 'CCF-000103',
    status: 'asentada',
    totalDebit: 2377.50,
    totalCredit: 2377.50,
    isBalanced: true,
    createdAt: '2026-08-21T11:45:00Z',
    lines: [
      {
        accountCode: '1103-01',
        accountName: 'Clientes Locales (CxC)',
        debit: 1852.50,
        credit: 0,
        concept: 'Cuenta por cobrar a Gabriela Zavaleta S.A. de C.V. (Crédito 30 días)',
      },
      {
        accountCode: '5101',
        accountName: 'Ingresos por Ventas Locales Gravadas',
        debit: 0,
        credit: 1625.00,
        concept: 'Venta neta software y consultoría',
      },
      {
        accountCode: '2107-01',
        accountName: 'IVA Débito Fiscal (Ventas Locales)',
        debit: 0,
        credit: 211.25,
        concept: 'Débito Fiscal 13% CCF-000103',
      },
      {
        accountCode: '2107-02',
        accountName: 'IVA Percibido 1%',
        debit: 0,
        credit: 16.25,
        concept: 'Percepción 1% aplicada al cliente',
      },
      {
        accountCode: '4101',
        accountName: 'Costo de Ventas (Mercaderías)',
        debit: 525.00,
        credit: 0,
        concept: 'Costo directo de implementación y licencias',
      },
      {
        accountCode: '1105-01',
        accountName: 'Mercaderías para la Venta (Bodega Central)',
        debit: 0,
        credit: 525.00,
        concept: 'Descargo de inventario por venta',
      },
    ],
  },
  {
    id: 'asiento_pur_1',
    companyId: 'comp_1',
    entryNumber: 6,
    date: '2026-08-03',
    concept: 'Compra s/g CCF N° CCF-49201 a Importadora Tecnológica Global S.A. de C.V.',
    sourceModule: 'compras',
    referenceDoc: 'CCF-49201',
    status: 'asentada',
    totalDebit: 4452.20,
    totalCredit: 4452.20,
    isBalanced: true,
    createdAt: '2026-08-03T09:00:00Z',
    lines: [
      {
        accountCode: '1105-01',
        accountName: 'Mercaderías para la Venta (Bodega Central)',
        debit: 3940.00,
        credit: 0,
        concept: 'Entrada a bodega de terminales POS y lectores',
      },
      {
        accountCode: '1108',
        accountName: 'IVA Crédito Fiscal (Compras y Gastos)',
        debit: 512.20,
        credit: 0,
        concept: 'Crédito Fiscal 13% soportado en compra',
      },
      {
        accountCode: '1101-03',
        accountName: 'Banco Agrícola - Operaciones Principales',
        debit: 0,
        credit: 4452.20,
        concept: 'Pago por transferencia a TechGlobal SV',
      },
    ],
  },
  {
    id: 'asiento_pur_2',
    companyId: 'comp_1',
    entryNumber: 7,
    date: '2026-08-14',
    concept: 'Compra s/g Factura Sujeto Excluido N° FSE-0012 a Lic. Mauricio Alexander Ramos',
    sourceModule: 'compras',
    referenceDoc: 'FSE-0012',
    status: 'asentada',
    totalDebit: 500.00,
    totalCredit: 500.00,
    isBalanced: true,
    createdAt: '2026-08-14T15:30:00Z',
    lines: [
      {
        accountCode: '4201-04',
        accountName: 'Honorarios y Servicios Profesionales',
        debit: 500.00,
        credit: 0,
        concept: 'Asesoría legal corporativa y notariado DTE',
      },
      {
        accountCode: '2108-04',
        accountName: 'Retención de Renta 10% Servicios Profesionales',
        debit: 0,
        credit: 50.00,
        concept: 'Retención de Renta 10% Art. 156 Código Tributario',
      },
      {
        accountCode: '1101-03',
        accountName: 'Banco Agrícola - Operaciones Principales',
        debit: 0,
        credit: 450.00,
        concept: 'Transferencia neta al profesional',
      },
    ],
  },
  {
    id: 'asiento_pur_3',
    companyId: 'comp_1',
    entryNumber: 8,
    date: '2026-08-19',
    concept: 'Compra s/g CCF N° CCF-88219 a Papelería e Impresos de Centroamérica S.A. de C.V.',
    sourceModule: 'compras',
    referenceDoc: 'CCF-88219',
    status: 'asentada',
    totalDebit: 1243.00,
    totalCredit: 1243.00,
    isBalanced: true,
    createdAt: '2026-08-19T11:00:00Z',
    lines: [
      {
        accountCode: '1105-01',
        accountName: 'Mercaderías para la Venta (Bodega Central)',
        debit: 1100.00,
        credit: 0,
        concept: 'Lote de 50 cajas de rollos térmicos DTE',
      },
      {
        accountCode: '1108',
        accountName: 'IVA Crédito Fiscal (Compras y Gastos)',
        debit: 143.00,
        credit: 0,
        concept: 'Crédito Fiscal 13% en compra a PapelCentro',
      },
      {
        accountCode: '2108-05',
        accountName: 'Retención IVA 1% Proveedores',
        debit: 0,
        credit: 11.00,
        concept: 'Retención 1% IVA efectuada por Gran Contribuyente',
      },
      {
        accountCode: '2101-01',
        accountName: 'Proveedores Locales (CxP)',
        debit: 0,
        credit: 1232.00,
        concept: 'Cuenta por pagar a Papelería e Impresos (Crédito 15 días)',
      },
    ],
  },
  {
    id: 'asiento_pay_01',
    companyId: 'comp_1',
    entryNumber: 9,
    date: '2026-08-15',
    concept: 'Planilla de Sueldos y Salarios 1a Quincena Agosto 2026 con Cargas Patronales',
    sourceModule: 'planilla',
    referenceDoc: 'PLAN-2026-08-Q1',
    status: 'asentada',
    totalDebit: 5159.06,
    totalCredit: 5159.06,
    isBalanced: true,
    createdAt: '2026-08-15T18:00:00Z',
    lines: [
      {
        accountCode: '4201-01',
        accountName: 'Sueldos y Salarios Administrativos',
        debit: 3850.00,
        credit: 0,
        concept: 'Sueldos devengados de la quincena',
      },
      {
        accountCode: '4201-02',
        accountName: 'Aportes Patronales ISSS y AFP',
        debit: 619.13,
        credit: 0,
        concept: 'Aporte Patronal ISSS (7.5%), AFP (8.75%) e INSAFORP (1%)',
      },
      {
        accountCode: '4201-03',
        accountName: 'Provisiones Laborales (Aguinaldo, Vacación e Indemnización)',
        debit: 689.93,
        credit: 0,
        concept: 'Provisión legal mensual de prestaciones sociales',
      },
      {
        accountCode: '2108-01',
        accountName: 'ISSS Retenido y Patronal por Pagar',
        debit: 0,
        credit: 341.25,
        concept: 'ISSS Laboral ($97.50) + Patronal ($243.75)',
      },
      {
        accountCode: '2108-02',
        accountName: 'AFP Retenida y Patronal por Pagar',
        debit: 0,
        credit: 616.01,
        concept: 'AFP Laboral ($279.13) + Patronal ($336.88)',
      },
      {
        accountCode: '2108-03',
        accountName: 'Impuesto sobre la Renta Retenido (Planilla)',
        debit: 0,
        credit: 285.10,
        concept: 'Retención de Renta empleados s/g tablas MH',
      },
      {
        accountCode: '2108-06',
        accountName: 'INSAFORP por Pagar',
        debit: 0,
        credit: 38.50,
        concept: 'Aporte patronal INSAFORP 1%',
      },
      {
        accountCode: '2109',
        accountName: 'Provisiones para Prestaciones Sociales por Pagar',
        debit: 0,
        credit: 689.93,
        concept: 'Acumulado de provisiones laborales',
      },
      {
        accountCode: '1101-03',
        accountName: 'Banco Agrícola - Operaciones Principales',
        debit: 0,
        credit: 3188.27,
        concept: 'Desembolso neto a empleados vía transferencia bancaria',
      },
    ],
  },
];

export const SAMPLE_OTHER_INCOMES: OtherIncome[] = [
  {
    id: 'inc_oth_1',
    companyId: 'comp_1',
    branchId: 'branch_1',
    branchName: 'Casa Matriz - Escalón',
    date: '2026-08-12',
    category: 'remanente_hacienda',
    categoryLabel: 'Devolución de Remanente Tributario (Ministerio de Hacienda)',
    description: 'Devolución de remanente a favor IVA/Pago a Cuenta ejercicio anterior F-07',
    amount: 1450.00,
    paymentMethod: 'transferencia',
    targetAccountId: 'bank_1',
    targetAccountName: 'Banco Agrícola - Cuenta Corriente Principal',
    referenceNumber: 'MH-DEV-2026-0881',
    notes: 'Acreditado directamente por DGC Ministerio de Hacienda a cuenta corriente.',
    createdAt: '2026-08-12T10:30:00Z',
  },
  {
    id: 'inc_oth_2',
    companyId: 'comp_1',
    branchId: 'branch_1',
    branchName: 'Casa Matriz - Escalón',
    date: '2026-08-18',
    category: 'venta_activo_fijo',
    categoryLabel: 'Venta de Activo Fijo / Mobiliario & Equipo',
    description: 'Venta de servidor Dell PowerEdge y equipos de computación dados de baja',
    amount: 850.00,
    paymentMethod: 'transferencia',
    targetAccountId: 'bank_1',
    targetAccountName: 'Banco Agrícola - Cuenta Corriente Principal',
    referenceNumber: 'VTA-AF-004',
    notes: 'Liquidación de activo fijo totalmente depreciado.',
    createdAt: '2026-08-18T14:15:00Z',
  },
  {
    id: 'inc_oth_3',
    companyId: 'comp_1',
    branchId: 'branch_2',
    branchName: 'Sucursal Santa Tecla',
    date: '2026-08-25',
    category: 'rendimiento_financiero',
    categoryLabel: 'Rendimientos Financieros & Intereses',
    description: 'Intereses ganados en cuenta de ahorro empresarial a plazo',
    amount: 320.00,
    paymentMethod: 'deposito',
    targetAccountId: 'bank_2',
    targetAccountName: 'Banco BAC Credomatic - Recaudo & Nómina',
    referenceNumber: 'INT-BAC-08',
    notes: 'Intereses bancarios netos acreditados.',
    createdAt: '2026-08-25T09:00:00Z',
  },
];

// ----------------------------------------------------
// DATOS MUESTRA: FINANZAS PERSONALES
// ----------------------------------------------------
export const SAMPLE_PERSONAL_TRANSACTIONS = [
  {
    id: 'pt_1',
    userId: 'user_personal',
    type: 'ingreso' as const,
    amount: 1250.00,
    category: 'Salario / Sueldo',
    concept: 'Pago quincena n.° 1 - Salario Profesional',
    date: '2026-09-01',
    paymentMethod: 'transferencia' as const,
    notes: 'Acreditación bancaria Banco Cuscatlán',
  },
  {
    id: 'pt_2',
    userId: 'user_personal',
    type: 'gasto' as const,
    amount: 350.00,
    category: 'Vivienda y Servicios',
    concept: 'Pago mensualidad de alquiler de apartamento',
    date: '2026-09-02',
    paymentMethod: 'transferencia' as const,
  },
  {
    id: 'pt_3',
    userId: 'user_personal',
    type: 'gasto' as const,
    amount: 145.80,
    category: 'Supermercado / Comida',
    concept: 'Compras de despensa mensual en Súper Selectos',
    date: '2026-09-03',
    paymentMethod: 'debito' as const,
  },
  {
    id: 'pt_4',
    userId: 'user_personal',
    type: 'gasto' as const,
    amount: 45.00,
    category: 'Vivienda y Servicios',
    concept: 'Recibo mensual de energía eléctrica CAESS',
    date: '2026-09-05',
    paymentMethod: 'debito' as const,
  },
  {
    id: 'pt_5',
    userId: 'user_personal',
    type: 'gasto' as const,
    amount: 40.00,
    category: 'Transporte y Gasolina',
    concept: 'Gasolina Especial estación Texaco Los Próceres',
    date: '2026-09-07',
    paymentMethod: 'debito' as const,
  },
  {
    id: 'pt_6',
    userId: 'user_personal',
    type: 'ingreso' as const,
    amount: 380.00,
    category: 'Honorarios / Freelance',
    concept: 'Diseño web y asesoría a cliente particular',
    date: '2026-09-10',
    paymentMethod: 'transferencia' as const,
    notes: 'Transferencia Transfer365',
  },
  {
    id: 'pt_7',
    userId: 'user_personal',
    type: 'gasto' as const,
    amount: 38.50,
    category: 'Entretenimiento y Ocio',
    concept: 'Cena fin de semana restaurante La Pampa',
    date: '2026-09-12',
    paymentMethod: 'credito' as const,
  },
  {
    id: 'pt_8',
    userId: 'user_personal',
    type: 'gasto' as const,
    amount: 25.00,
    category: 'Salud y Farmacia',
    concept: 'Vitaminas y medicamentos en Farmacias San Nicolás',
    date: '2026-09-14',
    paymentMethod: 'efectivo' as const,
  },
  {
    id: 'pt_9',
    userId: 'user_personal',
    type: 'ingreso' as const,
    amount: 1250.00,
    category: 'Salario / Sueldo',
    concept: 'Pago quincena n.° 2 - Salario Profesional',
    date: '2026-09-15',
    paymentMethod: 'transferencia' as const,
  },
  {
    id: 'pt_10',
    userId: 'user_personal',
    type: 'gasto' as const,
    amount: 110.00,
    category: 'Supermercado / Comida',
    concept: 'Verduras, frutas y carnes mercado local',
    date: '2026-09-16',
    paymentMethod: 'efectivo' as const,
  },
];

export const SAMPLE_PERSONAL_BUDGETS = [
  { id: 'pb_1', category: 'Supermercado / Comida', budgetedAmount: 350.00, icon: 'ShoppingCart' },
  { id: 'pb_2', category: 'Vivienda y Servicios', budgetedAmount: 480.00, icon: 'Home' },
  { id: 'pb_3', category: 'Transporte y Gasolina', budgetedAmount: 140.00, icon: 'Car' },
  { id: 'pb_4', category: 'Salud y Farmacia', budgetedAmount: 80.00, icon: 'HeartPulse' },
  { id: 'pb_5', category: 'Entretenimiento y Ocio', budgetedAmount: 120.00, icon: 'Film' },
  { id: 'pb_6', category: 'Educación y Cursos', budgetedAmount: 90.00, icon: 'GraduationCap' },
  { id: 'pb_7', category: 'Pago de Deudas / Tarjetas', budgetedAmount: 200.00, icon: 'CreditCard' },
];

export const SAMPLE_PERSONAL_GOALS = [
  {
    id: 'pg_1',
    title: 'Fondo de Emergencia (3 Meses de Gastos)',
    targetAmount: 2400.00,
    currentAmount: 1650.00,
    targetDate: '2026-12-31',
    category: 'Seguridad Financiera',
  },
  {
    id: 'pg_2',
    title: 'Vacaciones Fin de Año (Ruta de Las Flores / Playa)',
    targetAmount: 500.00,
    currentAmount: 320.00,
    targetDate: '2026-11-30',
    category: 'Recreación',
  },
  {
    id: 'pg_3',
    title: 'Prima para Vehículo / Renovación',
    targetAmount: 3500.00,
    currentAmount: 1800.00,
    targetDate: '2027-06-30',
    category: 'Patrimonio',
  },
];

// Servicios Profesionales (Art. 156 Código Tributario SV - 10% Retención Renta)
export const SAMPLE_PROFESSIONAL_SERVICES: ProfessionalServiceRecord[] = [
  {
    id: 'prof_1',
    companyId: 'comp_1',
    providerName: 'Lic. Claudia María Rivas Gómez',
    dui: '02891745-3',
    nit: '0614-120588-102-4',
    serviceConcept: 'Asesoría y Auditoría Financiera NIIF para PYMES',
    periodMonth: 9,
    periodYear: 2026,
    date: '2026-09-15',
    grossAmount: 850.00,
    retentionRate: 0.10,
    retentionAmount: 85.00,
    netAmount: 765.00,
    receiptNumber: 'REC-2026-042',
    status: 'pagado',
    paymentMethod: 'Transferencia Banco Agrícola',
    notes: 'Honorarios correspondientes a revisión de cierre contable Q3.',
    createdAt: '2026-09-15T10:00:00Z',
  },
  {
    id: 'prof_2',
    companyId: 'comp_1',
    providerName: 'Ing. Carlos Fernando Menjívar',
    dui: '04128934-8',
    nit: '0614-250892-101-7',
    serviceConcept: 'Consultoría en Ciberseguridad y Auditoría de Redes',
    periodMonth: 9,
    periodYear: 2026,
    date: '2026-09-20',
    grossAmount: 1200.00,
    retentionRate: 0.10,
    retentionAmount: 120.00,
    netAmount: 1080.00,
    receiptNumber: 'REC-2026-077',
    status: 'pendiente',
    paymentMethod: 'Cheque Banco Cuscatlán',
    notes: 'Implementación de políticas ISO 27001 para DTE.',
    createdAt: '2026-09-20T14:30:00Z',
  },
  {
    id: 'prof_3',
    companyId: 'comp_1',
    providerName: 'Licda. Sofia Elena Villalobos',
    dui: '03781290-5',
    nit: '0614-040391-103-2',
    serviceConcept: 'Servicios de Diseño Gráfico Corporativo y Branding',
    periodMonth: 9,
    periodYear: 2026,
    date: '2026-09-22',
    grossAmount: 600.00,
    retentionRate: 0.10,
    retentionAmount: 60.00,
    netAmount: 540.00,
    receiptNumber: 'REC-2026-091',
    status: 'pendiente',
    paymentMethod: 'Transferencia BAC Credomatic',
    notes: 'Manual de identidad y templates para redes sociales.',
    createdAt: '2026-09-22T16:00:00Z',
  },
];

// Carpetas de Reclutamiento / Vacantes
export const SAMPLE_CANDIDATE_FOLDERS: CandidateFolder[] = [
  {
    id: 'cf_1',
    companyId: 'comp_1',
    name: 'Asistente Administrativo y Recepción',
    department: 'Operaciones & RRHH',
    description: 'Proceso de selección para recepción, atención a clientes y apoyo de facturación.',
    createdAt: '2026-08-15',
  },
  {
    id: 'cf_2',
    companyId: 'comp_1',
    name: 'Diseño Gráfico & Manejo de Redes',
    department: 'Marketing & Publicidad',
    description: 'Búsqueda de diseñador gráfico creativo con experiencia en Illustrator, Photoshop y Reels.',
    createdAt: '2026-08-20',
  },
  {
    id: 'cf_3',
    companyId: 'comp_1',
    name: 'Cajero / Operador POS y Facturación',
    department: 'Ventas de Sucursal',
    description: 'Encargado de cobro rápido, arqueo de caja y emisión de DTEs en punto de venta.',
    createdAt: '2026-09-01',
  },
];

// Solicitantes / Candidatos con CV
export const SAMPLE_CANDIDATE_APPLICANTS: CandidateApplicant[] = [
  {
    id: 'cand_1',
    companyId: 'comp_1',
    folderId: 'cf_1',
    folderName: 'Asistente Administrativo y Recepción',
    fullName: 'Gabriela Michelle Orellana',
    email: 'gabriela.orellana@gmail.com',
    phone: '7829-1044',
    appliedDate: '2026-09-10',
    expectedSalary: 550.00,
    experienceYears: 3,
    educationLevel: 'Técnico en Administración de Empresas',
    status: 'entrevista',
    rating: 5,
    notes: 'Excelente presentación, proactiva, manejo fluido de Excel y atención al cliente presencial.',
    cvFileName: 'CV_Gabriela_Orellana_2026.pdf',
    cvSummaryOrUrl: 'Experiencia de 3 años en empresas comerciales, manejo de archivo, recepción de correspondencia y facturación básica.',
    skills: ['Atención al Cliente', 'Excel Intermedio', 'Facturación', 'Organización'],
    createdAt: '2026-09-10T09:00:00Z',
  },
  {
    id: 'cand_2',
    companyId: 'comp_1',
    folderId: 'cf_1',
    folderName: 'Asistente Administrativo y Recepción',
    fullName: 'Rodrigo Ernesto Vásquez',
    email: 'rodrigo.vasquez99@outlook.com',
    phone: '7190-2388',
    appliedDate: '2026-09-12',
    expectedSalary: 500.00,
    experienceYears: 1,
    educationLevel: 'Bachiller General con Diplomado',
    status: 'recibido',
    rating: 4,
    notes: 'Candidato con disposición de aprendizaje rápido y buena dicción telefónica.',
    cvFileName: 'CV_Rodrigo_Vasquez.pdf',
    cvSummaryOrUrl: 'Atención al cliente en call center 1 año, conocimientos de paquete Office y redacción.',
    skills: ['Conmutador', 'Digitación Rápida', 'Puntualidad'],
    createdAt: '2026-09-12T11:30:00Z',
  },
  {
    id: 'cand_3',
    companyId: 'comp_1',
    folderId: 'cf_2',
    folderName: 'Diseño Gráfico & Manejo de Redes',
    fullName: 'Andrea Marcela Henríquez',
    email: 'andrea.henriquez.design@gmail.com',
    phone: '7655-4321',
    appliedDate: '2026-09-14',
    expectedSalary: 700.00,
    experienceYears: 4,
    educationLevel: 'Licenciatura en Diseño Gráfico (Egresada)',
    status: 'seleccionado',
    rating: 5,
    notes: 'Portafolio muy completo, estilo visual moderno, domina Premiere Pro y After Effects para reels.',
    cvFileName: 'Portafolio_Andrea_Henriquez_2026.pdf',
    cvSummaryOrUrl: 'Portafolio web: behance.net/andrea_design_sv. Campañas para restaurantes y marcas de moda.',
    skills: ['Adobe Illustrator', 'Photoshop', 'CapCut / Premiere', 'Copywriting'],
    createdAt: '2026-09-14T14:15:00Z',
  },
];





